### ISSUE TITLE
missing page information for Google search results

### ISSUE THREAD

**Issue by peterstadler** [TEIC/infrastructure#2] opened 2022-03-09 09:17 UTC
Conal Tuohy reported on TEI-L:

> I was googling for the TEI <body> element trying to find the reference page for that element in the TEI guidelines just now, but the page I was hoping for was not returned in the first few results.
>
> Google claims that GoogleBot has been blocked from the page. I looked at https://tei-c.org/robots.txt and couldn't see a problem, but there definitely is something wrong: you can see the result here where I searched for the actual URL of the page and Google returns it with the message "No information is available for this page."
>
> https://www.google.com/search?q=https%3A%2F%2Ftei-c.org%2Frelease%2Fdoc%2Ftei-p5-doc%2Fen%2Fhtml%2FDS.html

**Comment by Conal-Tuohy** [comment] 2022-03-09 12:47
It's weird because there are plenty of other pages on the tei-c.org site which are properly indexed.

**Comment by StefanDumont** [comment] 2022-03-14 08:06
I can confirm Peters obersvation. I searched a couple of TEI elements in Google and the search results include max 1 result on tei-c.org - if at all.

Perhaps the "crawl delay" causes some problems? Google doesn't seem to support it ...

**Comment by hcayless** [comment] 2022-03-14 14:31
I've gotten the Google Search Console going for tei-c.org. It'll take a while for the reports to run. It clearly does have a problem with our robots.txt. I may try adding a directive explicitly allowing the GoogleBot access and see if that helps.

**Comment by Conal-Tuohy** [comment] 2022-04-06 07:21
It does seem to have come right, for whatever reason. Google is now displaying some useful data for the page I initially reported https://www.google.com/search?q=site%3Ahttps%3A%2F%2Ftei-c.org%2Frelease%2Fdoc%2Ftei-p5-doc%2Fen%2Fhtml%2FDS.html

**Comment by martinascholger** [comment] 2022-07-04 05:45
This seems to be solved, I'm closing the issue.

**Closed as completed by martinascholger** 2022-07-04 05:45 UTC
